version: "3.3"

services:
  mariadb-govwa:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_USER: govwauser
      MARIADB_PASSWORD: ${MYSQL_GOVWA_PASSWORD}
      MARIADB_DATABASE: govwa
    command: --init-file /docker-entrypoint-initdb.d/0_init.sql
    volumes:
      - ./db/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql
    networks:
      - my-network
  govwa:
    image: govwa:1.0
    build: .
    depends_on:
      - mariadb-govwa
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
      - ./log-govwa/:/var/log/govwa
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
